### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by kts707** [WindVChen/Diff-Harmonization#1]
Hi,

Thanks for the great work and the results are impressive! Are you planning to release the code soon? If so, what's the expected timeline/date? Thanks in advance!

**Comment by WindVChen** [comment]
Hi @kts707 ,

Thanks a bunch for showing interest in our work! Right now, we're actually knee-deep in [**another harmonization repository**](https://github.com/WindVChen/INR-Harmonization) (feel free to check it out if you're curious!). Once we've finished that, we'll dive right into the next phase of this repository.

So, hang tight! I'll be polishing up the current method and aiming to drop the code before September hits.

Thanks again, and have a fantastic day! 😊

**Comment by kts707** [comment]
Thanks! Looking forward to the release!

**Comment by WindVChen** [comment]
Hi @kts707 ,

Exciting update! Our code is now live in the repository. Apologies for slightly missing the 'before September' target, but we made it just in the nick of time! 😃 Enjoy digging into the code! 🚀

_(We're not stopping here though – there are more improvements in the pipeline. So, stay tuned for upcoming updates.)_

**Comment by kts707** [comment]
Thanks so much for the notice, and looking forward to the upcoming improvements!
