### ISSUE TITLE
Stable Diffusion Version

### ISSUE THREAD

**Issue by connorzl** [WindVChen/Diff-Harmonization#3]
Hi, I downloaded the Stable Diffusion pretrained models from here: https://huggingface.co/stabilityai/stable-diffusion-2-base/tree/main

However, I think that the version is slightly different, as I had to change the module lookup to the following, otherwise none of the forward functions were being swapped out:

        #if net_.__class__.__name__ == 'CrossAttention':
        if 'CrossAttn' in net_.__class__.__name__:
            net_.forward = ca_forward(net_, place_in_unet)
            return count + 1

This causes other errors in the code, so I was wondering if you could provide the link to the pre-trained stable diffusion model you are using. 

Thanks!

**Comment by connorzl** [comment]
Ah, I figured it out by looking at the answer in this thread: https://github.com/google/prompt-to-prompt/issues/57#issuecomment-1573380432

`pip install diffusers==0.10.0`

**Comment by WindVChen** [comment]
Hi @connorzl,

Glad to see the problem solved. In our implementation, we use `diffusers==0.9.0` as displayed in [requirements.txt](https://github.com/WindVChen/Diff-Harmonization/blob/main/requirements.txt). We have not tested `diffusers==0.10.0`, but it may also work.
