### ISSUE TITLE
KeyError: 'up_cross'

### ISSUE THREAD

**Issue by wzking09** [WindVChen/Diff-Harmonization#4]
Hi, when I do this with pretrained model :
python main.py --harmonize_iterations 10 --save_dir "./output" --is_single_image --image_path "./demo/girl_comp.jpg" --mask_path "./demo/girl_mask.jpg" --foreground_prompt "girl autumn" --background_prompt "girl winter" --pretrained_diffusion_path "stabilityai/stable-diffusion-2-base"
it says no keys 'up_cross' in attention_maps (utils.py, line 115) during first iteration. It seems attention_map is empty. Can you please help me figure out? Many thanks~

**Comment by WindVChen** [comment]
Hi @wzking09 ,

Could you please check your version of the `diffusers` package? There are some significant changes in newer `diffusers` which may lead to incompatibility with our code. The code should run smoothly under `diffusers==0.9.0` (as shown in [requirements.txt](https://github.com/WindVChen/Diff-Harmonization/blob/main/requirements.txt)).

Hope this can help.

**Comment by wzking09** [comment]
It works! thanks a lot :)
