### ISSUE TITLE
unrecognized arguments error

### ISSUE THREAD

**Issue by msskaa12** [WindVChen/Diff-Harmonization#5]
thanks for this aswesome work .  when I run this code , I  got unrecognized arguments error,  what is the problem? 
I had mannually download the pretrained molel in ./stabilityai/stable-diffusion-2-base/512-base-ema.safetensors

python main.py --harmonize_iterations 10 --save_dir "./output" --is_single_image --image_path "./demo/girl_comp.jpg" --mask_path "./demo/girl_mask.jpg" --foreground_prompt "girl autumn" --background_prompt "girl winter" --pretrained_diffusion_path "./stabilityai/stable-diffusion-2-base/512-base-ema.safetensors" --use_edge_map
usage: main.py [-h] [--pidinet_model PIDINET_MODEL] [--sa] [--dil] [--config CONFIG] [--evaluate EVALUATE] [--gpu GPU]
main.py: error: unrecognized arguments: --harmonize_iterations 10 --save_dir ./output --is_single_image --image_path ./demo/girl_comp.jpg --mask_path ./demo/girl_mask.jpg --foreground_prompt girl autumn --background_prompt girl winter --pretrained_diffusion_path ./stabilityai/stable-diffusion-2-base/512-base-ema.safetensors --use_edge_map

**Comment by WindVChen** [comment]
Hi @msskaa12 ,

Thanks for catching that bug! It's been fixed in the latest commit. You can grab the updated code or just make the same changes as shown [here](https://github.com/WindVChen/Diff-Harmonization/commit/7d469e698924c27bf9f8e35d12c37296185e30b7). It should work.

Cheers.

**Comment by msskaa12** [comment]
Thanks for your prompt reply. It works
