### ISSUE TITLE
KeyError: 'up_cross'

### ISSUE THREAD

**Issue by msskaa12** [WindVChen/Diff-Harmonization#6]
I got an error  KeyError: 'up_cross'  ,  
here is github copilot suggestion, my knowledge adbout transformer is very poor , may be it had something should be fix?
![Screenshot from 2024-05-04 13-31-25](https://github.com/WindVChen/Diff-Harmonization/assets/78275037/7e2624fc-ce88-46e8-a826-e38ba360b861)

**Comment by WindVChen** [comment]
Hi @msskaa12 ,

It seems a 'diffusers' version problem similar as https://github.com/WindVChen/Diff-Harmonization/issues/4? Hope that helps.
